export const API_PATHS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    REFRESH: '/auth/refresh',
    ME: '/auth/me',
    LOGOUT: '/auth/logout',
  },
  CATEGORIES: {
    LIST: '/categories',
  },
  PRODUCTS: {
    LIST: '/products',
    DETAIL: (id: string) => `/products/${id}`,
  },
  PRODUCT_VIEWS: {
    CREATE: '/product-views',
  },
  CART: {
    GET: '/cart',
    ADD_ITEM: '/cart/items',
    UPDATE_ITEM: (id: string) => `/cart/items/${id}`,
    REMOVE_ITEM: (id: string) => `/cart/items/${id}`,
  },
  VOUCHERS: {
    VALIDATE: '/vouchers/validate',
  },
  CHECKOUT: {
    CREATE: '/checkout',
  },
  CASHBACK: {
    CONFIG: '/cashback/config',
    CONNECTION: '/cashback/connection',
    LOGIN: '/cashback/connection/login',
    TWO_FACTOR: '/cashback/connection/login/2fa',
    TWO_FACTOR_RESEND: '/cashback/connection/login/2fa/resend',
    VERIFY_EMAIL: '/cashback/connection/verify-email',
    VERIFY_EMAIL_RESEND: '/cashback/connection/verify-email/resend',
    LINK: '/cashback/link',
    ACCOUNT: '/cashback/account',
    ORDERS: '/cashback/orders',
    ORDER_DETAIL: (id: string) => `/cashback/orders/${id}`,
    WITHDRAWALS: '/cashback/withdrawals',
    WITHDRAWAL_OTP: '/cashback/withdrawals/otp',
    PAYMENT_ACCOUNTS: '/cashback/payment-accounts',
    PAYMENT_ACCOUNT_DETAIL: (id: string) => `/cashback/payment-accounts/${id}`,
    PAYMENT_ACCOUNT_DEFAULT: (id: string) => `/cashback/payment-accounts/${id}/default`,
    REFERRALS: '/cashback/referrals',
    BALANCE_LOGS: '/cashback/balance-logs',
  },
  ADMIN: {
    DASHBOARD_OVERVIEW: '/admin/dashboard/overview',
    REPORTS_SUMMARY: '/admin/reports/summary',
    AUDIT_LOGS: '/admin/audit-logs',
    ACCOUNTS: '/admin/accounts',
    ACCOUNT_DETAIL: (id: string) => `/admin/accounts/${id}`,
    ROLES: '/admin/roles',
    CATEGORIES: '/admin/categories',
    CATEGORY_DETAIL: (id: string) => `/admin/categories/${id}`,
    PRODUCTS: '/admin/products',
    PRODUCT_DETAIL: (id: string) => `/admin/products/${id}`,
    PRODUCT_VARIANTS: (id: string) => `/admin/products/${id}/variants`,
    VARIANT_DETAIL: (id: string) => `/admin/variants/${id}`,
    INVENTORY_ITEMS: '/admin/inventory-items',
    INVENTORY_ITEM_DETAIL: (id: string) => `/admin/inventory-items/${id}`,
    ORDERS: '/admin/orders',
    ORDER_DETAIL: (id: string) => `/admin/orders/${id}`,
    ORDER_STATUS: (id: string) => `/admin/orders/${id}/status`,
    ORDER_REFUND: (id: string) => `/admin/orders/${id}/refund`,
    VOUCHERS: '/admin/vouchers',
    VOUCHER_DETAIL: (id: string) => `/admin/vouchers/${id}`,
    PAYMENT_TRANSACTIONS: '/admin/payment-transactions',
    PAYMENT_TRANSACTION_DETAIL: (id: string) => `/admin/payment-transactions/${id}`,
    WALLET_LEDGERS: '/admin/wallet-ledgers',
  },
} as const;
